#!/usr/bin/python

import sys
import s3logparser

if len(sys.argv) == 3:
    s3l = s3logparser.S3LogParser(sys.argv[1], sys.argv[2])
else:
    raise Exception("Use this tool like:\n"
                    "$ s3lp <log_dir> <output_csv_file>")

s3l.build_data(s3logparser.popular_files)
s3l.to_csv()
